# Generated by Django 6.0.3 on 2026-03-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mostra', '0002_projeto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='area',
            field=models.CharField(choices=[('TEC', 'Tecnologia'), ('SAU', 'Saúde'), ('EDU', 'Educação'), ('HUM', 'Humanas')], default='TEC', max_length=3),
        ),
    ]
