# Generated by Django 6.0.3 on 2026-03-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mostra', '0003_projeto_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='resumo',
        ),
        migrations.AddField(
            model_name='projeto',
            name='conteudo_completo',
            field=models.TextField(blank=True, default='', help_text='Descrição detalhada que aparece na página interna'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='resumo_curto',
            field=models.TextField(blank=True, default='', help_text='Aparece no card da lista', max_length=300),
        ),
    ]
