# Generated by Django 6.0.3 on 2026-03-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mostra', '0004_remove_projeto_resumo_projeto_conteudo_completo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='arquivo_pdf',
            field=models.FileField(blank=True, help_text='Upload do artigo ou banner', null=True, upload_to='projetos/pdfs/'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='link_externo',
            field=models.URLField(blank=True, help_text='Link para vídeo no YouTube ou site', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='projetos/fotos/'),
        ),
    ]
