# Generated by Django 6.0.3 on 2026-03-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mostra', '0005_projeto_arquivo_pdf_projeto_link_externo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Evento')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_evento', models.DateTimeField(verbose_name='Data e Hora')),
                ('local_ou_link', models.CharField(max_length=255, verbose_name='Local ou Link da Live')),
                ('categoria', models.CharField(choices=[('LIVE', 'Live/Webinário'), ('DEFESA', 'Defesa de TCC'), ('PALESTRA', 'Palestra/Workshop')], default='LIVE', max_length=10)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['data_evento'],
            },
        ),
    ]
