# Generated by Django 6.0.3 on 2026-03-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mostra', '0006_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinhaPesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Linha')),
                ('descricao', models.TextField(verbose_name='Descrição da Linha')),
                ('cor_card', models.CharField(default='#b8a2e7', help_text='Cor em HEX (ex: #b8a2e7)', max_length=20)),
            ],
            options={
                'verbose_name': 'Linha de Pesquisa',
                'verbose_name_plural': 'Linhas de Pesquisa',
            },
        ),
    ]
