# Generated by Django 6.0.3 on 2026-03-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mostra', '0007_linhapesquisa'),
    ]

    operations = [
        migrations.AddField(
            model_name='linhapesquisa',
            name='conteudo_detalhado',
            field=models.TextField(blank=True, help_text='O texto detalhado que aparecerá quando o usuário clicar no card', null=True, verbose_name='Conteúdo Completo'),
        ),
        migrations.AddField(
            model_name='linhapesquisa',
            name='equipe',
            field=models.TextField(blank=True, help_text='Nomes e cargos dos membros da equipe', null=True, verbose_name='Equipe / Pesquisadores'),
        ),
        migrations.AddField(
            model_name='linhapesquisa',
            name='situacao',
            field=models.CharField(default='Em execução', help_text='Ex: Em andamento, Concluído, Planejamento', max_length=100, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='linhapesquisa',
            name='descricao',
            field=models.TextField(help_text='Aparece no card colorido da lista', verbose_name='Descrição Curta (Card)'),
        ),
    ]
