# Generated by Django 6.0.3 on 2026-03-28 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mostra', '0008_linhapesquisa_conteudo_detalhado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linhapesquisa',
            name='equipe',
        ),
        migrations.AlterField(
            model_name='linhapesquisa',
            name='conteudo_detalhado',
            field=models.TextField(blank=True, help_text='O texto detalhado que aparecerá na página interna da pesquisa', null=True, verbose_name='Conteúdo Completo'),
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('cargo', models.CharField(help_text='Ex: Coordenador, Pesquisador, Bolsista', max_length=100, verbose_name='Cargo/Função')),
                ('foto', models.ImageField(blank=True, help_text='Opcional. Se não enviar, um ícone padrão será exibido.', null=True, upload_to='pesquisadores/fotos/', verbose_name='Foto de Perfil')),
                ('linha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='mostra.linhapesquisa', verbose_name='Linha de Pesquisa')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
            },
        ),
    ]
